version: 5.0.{build}
image:
  - Visual Studio 2019
  - Ubuntu
skip_tags: true
configuration: Release
nuget:
  account_feed: true
  project_feed: true
before_build:
  - ps: >-
      nuget restore

build:
  project: OpenXmlPowerTools.sln
  verbosity: minimal

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  package_version: "{version}-prerelease"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"

artifacts:
  - path: '**\OpenXmlPowerToolsStandard.*.nupkg'

deploy:
  - provider: NuGet
    api_key:
      secure: BAGacXk+5m7jd8EvWW6wkYhoVml39WAi7n2Z0odVUKUq5SeWLqixvkPA1I+KbQ1r
    on:
      branch: master
  - provider: GitHub
    auth_token:
      secure: 6WIcUQnv2ZAHI7MaJeiopONTvv3TxZiaThY17jVC4tJTnva7F66tPqvCWX2kQRyM
    prerelease: true
